// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'smart_warmth_2025';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String BOOTSPLASH_LOGO = 'assets/bootsplash_logo.png';
  static const String BOOTSPLASH_LOGO_1200 = 'assets/bootsplash_logo_1200.png';
  static const String BOOTSPLASH_LOGO_450 = 'assets/bootsplash_logo_450.png';
  static const String BOOTSPLASH_LOGO_600 = 'assets/bootsplash_logo_600.png';
  static const String BOOTSPLASH_LOGO_900 = 'assets/bootsplash_logo_900.png';
  static const String BOOTSPLASH_MANIFEST = 'assets/bootsplash_manifest.json';
  static const String LOGO_APP = 'assets/images/logo_app.png';
}
